<?xml version="1.0" encoding="utf-8"?><Database Name="Auth564" EntityNamespace="IITBlog.Classes" Class="BlogDataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=brookfield.rice.iit.edu,8081;Initial Catalog=Auth564;User ID=student" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="Auth564" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Blog" Member="Blogs">
    <Type Name="Blog">
      <Column Name="BlogID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BlogText" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="Mood" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="UserID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ApplicationID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="RecCreationTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ApplicationName" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="PeopleID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>