//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("Auth564Model", "FK_people_peopleSalutationTypes", "peopleSalutationTypes", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Entity.peopleSalutationType), "people", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Entity.person), true)]
[assembly: EdmRelationshipAttribute("Auth564Model", "FK_peopleLogons_people", "people", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Entity.person), "peopleLogons", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Entity.peopleLogon), true)]
[assembly: EdmRelationshipAttribute("Auth564Model", "FK_Roles_people", "people", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Entity.person), "roles", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Entity.role), true)]
[assembly: EdmRelationshipAttribute("Auth564Model", "FK_Roles_RoleTypes", "roleTypes", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Entity.roleType), "roles", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Entity.role), true)]

#endregion

namespace Entity
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Auth564Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Auth564Entities object using the connection string found in the 'Auth564Entities' section of the application configuration file.
        /// </summary>
        public Auth564Entities() : base("name=Auth564Entities", "Auth564Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Auth564Entities object.
        /// </summary>
        public Auth564Entities(string connectionString) : base(connectionString, "Auth564Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Auth564Entities object.
        /// </summary>
        public Auth564Entities(EntityConnection connection) : base(connection, "Auth564Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<person> people
        {
            get
            {
                if ((_people == null))
                {
                    _people = base.CreateObjectSet<person>("people");
                }
                return _people;
            }
        }
        private ObjectSet<person> _people;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<peopleLogon> peopleLogons
        {
            get
            {
                if ((_peopleLogons == null))
                {
                    _peopleLogons = base.CreateObjectSet<peopleLogon>("peopleLogons");
                }
                return _peopleLogons;
            }
        }
        private ObjectSet<peopleLogon> _peopleLogons;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<peopleSalutationType> peopleSalutationTypes
        {
            get
            {
                if ((_peopleSalutationTypes == null))
                {
                    _peopleSalutationTypes = base.CreateObjectSet<peopleSalutationType>("peopleSalutationTypes");
                }
                return _peopleSalutationTypes;
            }
        }
        private ObjectSet<peopleSalutationType> _peopleSalutationTypes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<role> roles
        {
            get
            {
                if ((_roles == null))
                {
                    _roles = base.CreateObjectSet<role>("roles");
                }
                return _roles;
            }
        }
        private ObjectSet<role> _roles;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<roleType> roleTypes
        {
            get
            {
                if ((_roleTypes == null))
                {
                    _roleTypes = base.CreateObjectSet<roleType>("roleTypes");
                }
                return _roleTypes;
            }
        }
        private ObjectSet<roleType> _roleTypes;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the people EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTopeople(person person)
        {
            base.AddObject("people", person);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the peopleLogons EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTopeopleLogons(peopleLogon peopleLogon)
        {
            base.AddObject("peopleLogons", peopleLogon);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the peopleSalutationTypes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTopeopleSalutationTypes(peopleSalutationType peopleSalutationType)
        {
            base.AddObject("peopleSalutationTypes", peopleSalutationType);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the roles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToroles(role role)
        {
            base.AddObject("roles", role);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the roleTypes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToroleTypes(roleType roleType)
        {
            base.AddObject("roleTypes", roleType);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Auth564Model", Name="peopleLogon")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class peopleLogon : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new peopleLogon object.
        /// </summary>
        /// <param name="peopleLogonID">Initial value of the peopleLogonID property.</param>
        /// <param name="peopleID">Initial value of the peopleID property.</param>
        /// <param name="recCreationDate">Initial value of the recCreationDate property.</param>
        public static peopleLogon CreatepeopleLogon(global::System.Int32 peopleLogonID, global::System.Int32 peopleID, global::System.DateTime recCreationDate)
        {
            peopleLogon peopleLogon = new peopleLogon();
            peopleLogon.peopleLogonID = peopleLogonID;
            peopleLogon.peopleID = peopleID;
            peopleLogon.recCreationDate = recCreationDate;
            return peopleLogon;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 peopleLogonID
        {
            get
            {
                return _peopleLogonID;
            }
            set
            {
                if (_peopleLogonID != value)
                {
                    OnpeopleLogonIDChanging(value);
                    ReportPropertyChanging("peopleLogonID");
                    _peopleLogonID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("peopleLogonID");
                    OnpeopleLogonIDChanged();
                }
            }
        }
        private global::System.Int32 _peopleLogonID;
        partial void OnpeopleLogonIDChanging(global::System.Int32 value);
        partial void OnpeopleLogonIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 peopleID
        {
            get
            {
                return _peopleID;
            }
            set
            {
                OnpeopleIDChanging(value);
                ReportPropertyChanging("peopleID");
                _peopleID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("peopleID");
                OnpeopleIDChanged();
            }
        }
        private global::System.Int32 _peopleID;
        partial void OnpeopleIDChanging(global::System.Int32 value);
        partial void OnpeopleIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime recCreationDate
        {
            get
            {
                return _recCreationDate;
            }
            set
            {
                OnrecCreationDateChanging(value);
                ReportPropertyChanging("recCreationDate");
                _recCreationDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("recCreationDate");
                OnrecCreationDateChanged();
            }
        }
        private global::System.DateTime _recCreationDate;
        partial void OnrecCreationDateChanging(global::System.DateTime value);
        partial void OnrecCreationDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> logonTime
        {
            get
            {
                return _logonTime;
            }
            set
            {
                OnlogonTimeChanging(value);
                ReportPropertyChanging("logonTime");
                _logonTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("logonTime");
                OnlogonTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _logonTime;
        partial void OnlogonTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnlogonTimeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Auth564Model", "FK_peopleLogons_people", "people")]
        public person person
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<person>("Auth564Model.FK_peopleLogons_people", "people").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<person>("Auth564Model.FK_peopleLogons_people", "people").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<person> personReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<person>("Auth564Model.FK_peopleLogons_people", "people");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<person>("Auth564Model.FK_peopleLogons_people", "people", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Auth564Model", Name="peopleSalutationType")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class peopleSalutationType : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new peopleSalutationType object.
        /// </summary>
        /// <param name="salutationID">Initial value of the salutationID property.</param>
        /// <param name="salutationLong">Initial value of the salutationLong property.</param>
        public static peopleSalutationType CreatepeopleSalutationType(global::System.Int32 salutationID, global::System.String salutationLong)
        {
            peopleSalutationType peopleSalutationType = new peopleSalutationType();
            peopleSalutationType.salutationID = salutationID;
            peopleSalutationType.salutationLong = salutationLong;
            return peopleSalutationType;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 salutationID
        {
            get
            {
                return _salutationID;
            }
            set
            {
                if (_salutationID != value)
                {
                    OnsalutationIDChanging(value);
                    ReportPropertyChanging("salutationID");
                    _salutationID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("salutationID");
                    OnsalutationIDChanged();
                }
            }
        }
        private global::System.Int32 _salutationID;
        partial void OnsalutationIDChanging(global::System.Int32 value);
        partial void OnsalutationIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String salutation
        {
            get
            {
                return _salutation;
            }
            set
            {
                OnsalutationChanging(value);
                ReportPropertyChanging("salutation");
                _salutation = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("salutation");
                OnsalutationChanged();
            }
        }
        private global::System.String _salutation;
        partial void OnsalutationChanging(global::System.String value);
        partial void OnsalutationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String salutationLong
        {
            get
            {
                return _salutationLong;
            }
            set
            {
                OnsalutationLongChanging(value);
                ReportPropertyChanging("salutationLong");
                _salutationLong = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("salutationLong");
                OnsalutationLongChanged();
            }
        }
        private global::System.String _salutationLong;
        partial void OnsalutationLongChanging(global::System.String value);
        partial void OnsalutationLongChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Auth564Model", "FK_people_peopleSalutationTypes", "people")]
        public EntityCollection<person> people
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<person>("Auth564Model.FK_people_peopleSalutationTypes", "people");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<person>("Auth564Model.FK_people_peopleSalutationTypes", "people", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Auth564Model", Name="person")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class person : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new person object.
        /// </summary>
        /// <param name="peopleID">Initial value of the peopleID property.</param>
        /// <param name="logonName">Initial value of the logonName property.</param>
        /// <param name="passwd">Initial value of the passwd property.</param>
        /// <param name="recCreationDate">Initial value of the recCreationDate property.</param>
        public static person Createperson(global::System.Int32 peopleID, global::System.String logonName, global::System.String passwd, global::System.DateTime recCreationDate)
        {
            person person = new person();
            person.peopleID = peopleID;
            person.logonName = logonName;
            person.passwd = passwd;
            person.recCreationDate = recCreationDate;
            return person;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 peopleID
        {
            get
            {
                return _peopleID;
            }
            set
            {
                if (_peopleID != value)
                {
                    OnpeopleIDChanging(value);
                    ReportPropertyChanging("peopleID");
                    _peopleID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("peopleID");
                    OnpeopleIDChanged();
                }
            }
        }
        private global::System.Int32 _peopleID;
        partial void OnpeopleIDChanging(global::System.Int32 value);
        partial void OnpeopleIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> salutationID
        {
            get
            {
                return _salutationID;
            }
            set
            {
                OnsalutationIDChanging(value);
                ReportPropertyChanging("salutationID");
                _salutationID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("salutationID");
                OnsalutationIDChanged();
            }
        }
        private Nullable<global::System.Int32> _salutationID;
        partial void OnsalutationIDChanging(Nullable<global::System.Int32> value);
        partial void OnsalutationIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String firstName
        {
            get
            {
                return _firstName;
            }
            set
            {
                OnfirstNameChanging(value);
                ReportPropertyChanging("firstName");
                _firstName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("firstName");
                OnfirstNameChanged();
            }
        }
        private global::System.String _firstName;
        partial void OnfirstNameChanging(global::System.String value);
        partial void OnfirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String lastName
        {
            get
            {
                return _lastName;
            }
            set
            {
                OnlastNameChanging(value);
                ReportPropertyChanging("lastName");
                _lastName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("lastName");
                OnlastNameChanged();
            }
        }
        private global::System.String _lastName;
        partial void OnlastNameChanging(global::System.String value);
        partial void OnlastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String logonName
        {
            get
            {
                return _logonName;
            }
            set
            {
                OnlogonNameChanging(value);
                ReportPropertyChanging("logonName");
                _logonName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("logonName");
                OnlogonNameChanged();
            }
        }
        private global::System.String _logonName;
        partial void OnlogonNameChanging(global::System.String value);
        partial void OnlogonNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String passwd
        {
            get
            {
                return _passwd;
            }
            set
            {
                OnpasswdChanging(value);
                ReportPropertyChanging("passwd");
                _passwd = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("passwd");
                OnpasswdChanged();
            }
        }
        private global::System.String _passwd;
        partial void OnpasswdChanging(global::System.String value);
        partial void OnpasswdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime recCreationDate
        {
            get
            {
                return _recCreationDate;
            }
            set
            {
                OnrecCreationDateChanging(value);
                ReportPropertyChanging("recCreationDate");
                _recCreationDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("recCreationDate");
                OnrecCreationDateChanged();
            }
        }
        private global::System.DateTime _recCreationDate;
        partial void OnrecCreationDateChanging(global::System.DateTime value);
        partial void OnrecCreationDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> recModifedDate
        {
            get
            {
                return _recModifedDate;
            }
            set
            {
                OnrecModifedDateChanging(value);
                ReportPropertyChanging("recModifedDate");
                _recModifedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("recModifedDate");
                OnrecModifedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _recModifedDate;
        partial void OnrecModifedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnrecModifedDateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Auth564Model", "FK_people_peopleSalutationTypes", "peopleSalutationTypes")]
        public peopleSalutationType peopleSalutationType
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<peopleSalutationType>("Auth564Model.FK_people_peopleSalutationTypes", "peopleSalutationTypes").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<peopleSalutationType>("Auth564Model.FK_people_peopleSalutationTypes", "peopleSalutationTypes").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<peopleSalutationType> peopleSalutationTypeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<peopleSalutationType>("Auth564Model.FK_people_peopleSalutationTypes", "peopleSalutationTypes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<peopleSalutationType>("Auth564Model.FK_people_peopleSalutationTypes", "peopleSalutationTypes", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Auth564Model", "FK_peopleLogons_people", "peopleLogons")]
        public EntityCollection<peopleLogon> peopleLogons
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<peopleLogon>("Auth564Model.FK_peopleLogons_people", "peopleLogons");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<peopleLogon>("Auth564Model.FK_peopleLogons_people", "peopleLogons", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Auth564Model", "FK_Roles_people", "roles")]
        public EntityCollection<role> roles
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<role>("Auth564Model.FK_Roles_people", "roles");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<role>("Auth564Model.FK_Roles_people", "roles", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Auth564Model", Name="role")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class role : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new role object.
        /// </summary>
        /// <param name="roleID">Initial value of the RoleID property.</param>
        /// <param name="peopleID">Initial value of the PeopleID property.</param>
        /// <param name="roleTypeID">Initial value of the RoleTypeID property.</param>
        /// <param name="roleActive">Initial value of the roleActive property.</param>
        /// <param name="recCreationDate">Initial value of the recCreationDate property.</param>
        public static role Createrole(global::System.Int32 roleID, global::System.Int32 peopleID, global::System.Int32 roleTypeID, global::System.Boolean roleActive, global::System.DateTime recCreationDate)
        {
            role role = new role();
            role.RoleID = roleID;
            role.PeopleID = peopleID;
            role.RoleTypeID = roleTypeID;
            role.roleActive = roleActive;
            role.recCreationDate = recCreationDate;
            return role;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RoleID
        {
            get
            {
                return _RoleID;
            }
            set
            {
                if (_RoleID != value)
                {
                    OnRoleIDChanging(value);
                    ReportPropertyChanging("RoleID");
                    _RoleID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RoleID");
                    OnRoleIDChanged();
                }
            }
        }
        private global::System.Int32 _RoleID;
        partial void OnRoleIDChanging(global::System.Int32 value);
        partial void OnRoleIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PeopleID
        {
            get
            {
                return _PeopleID;
            }
            set
            {
                OnPeopleIDChanging(value);
                ReportPropertyChanging("PeopleID");
                _PeopleID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PeopleID");
                OnPeopleIDChanged();
            }
        }
        private global::System.Int32 _PeopleID;
        partial void OnPeopleIDChanging(global::System.Int32 value);
        partial void OnPeopleIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RoleTypeID
        {
            get
            {
                return _RoleTypeID;
            }
            set
            {
                OnRoleTypeIDChanging(value);
                ReportPropertyChanging("RoleTypeID");
                _RoleTypeID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RoleTypeID");
                OnRoleTypeIDChanged();
            }
        }
        private global::System.Int32 _RoleTypeID;
        partial void OnRoleTypeIDChanging(global::System.Int32 value);
        partial void OnRoleTypeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean roleActive
        {
            get
            {
                return _roleActive;
            }
            set
            {
                OnroleActiveChanging(value);
                ReportPropertyChanging("roleActive");
                _roleActive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("roleActive");
                OnroleActiveChanged();
            }
        }
        private global::System.Boolean _roleActive;
        partial void OnroleActiveChanging(global::System.Boolean value);
        partial void OnroleActiveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime recCreationDate
        {
            get
            {
                return _recCreationDate;
            }
            set
            {
                OnrecCreationDateChanging(value);
                ReportPropertyChanging("recCreationDate");
                _recCreationDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("recCreationDate");
                OnrecCreationDateChanged();
            }
        }
        private global::System.DateTime _recCreationDate;
        partial void OnrecCreationDateChanging(global::System.DateTime value);
        partial void OnrecCreationDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> recModifiedDate
        {
            get
            {
                return _recModifiedDate;
            }
            set
            {
                OnrecModifiedDateChanging(value);
                ReportPropertyChanging("recModifiedDate");
                _recModifiedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("recModifiedDate");
                OnrecModifiedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _recModifiedDate;
        partial void OnrecModifiedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnrecModifiedDateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Auth564Model", "FK_Roles_people", "people")]
        public person person
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<person>("Auth564Model.FK_Roles_people", "people").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<person>("Auth564Model.FK_Roles_people", "people").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<person> personReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<person>("Auth564Model.FK_Roles_people", "people");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<person>("Auth564Model.FK_Roles_people", "people", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Auth564Model", "FK_Roles_RoleTypes", "roleTypes")]
        public roleType roleType
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<roleType>("Auth564Model.FK_Roles_RoleTypes", "roleTypes").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<roleType>("Auth564Model.FK_Roles_RoleTypes", "roleTypes").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<roleType> roleTypeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<roleType>("Auth564Model.FK_Roles_RoleTypes", "roleTypes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<roleType>("Auth564Model.FK_Roles_RoleTypes", "roleTypes", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Auth564Model", Name="roleType")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class roleType : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new roleType object.
        /// </summary>
        /// <param name="roleTypeID">Initial value of the RoleTypeID property.</param>
        /// <param name="roleTypeName">Initial value of the RoleTypeName property.</param>
        /// <param name="roleTypeHier">Initial value of the RoleTypeHier property.</param>
        /// <param name="roleTypeActive">Initial value of the roleTypeActive property.</param>
        /// <param name="recCreationDate">Initial value of the recCreationDate property.</param>
        public static roleType CreateroleType(global::System.Int32 roleTypeID, global::System.String roleTypeName, global::System.Int32 roleTypeHier, global::System.Boolean roleTypeActive, global::System.DateTime recCreationDate)
        {
            roleType roleType = new roleType();
            roleType.RoleTypeID = roleTypeID;
            roleType.RoleTypeName = roleTypeName;
            roleType.RoleTypeHier = roleTypeHier;
            roleType.roleTypeActive = roleTypeActive;
            roleType.recCreationDate = recCreationDate;
            return roleType;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RoleTypeID
        {
            get
            {
                return _RoleTypeID;
            }
            set
            {
                if (_RoleTypeID != value)
                {
                    OnRoleTypeIDChanging(value);
                    ReportPropertyChanging("RoleTypeID");
                    _RoleTypeID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RoleTypeID");
                    OnRoleTypeIDChanged();
                }
            }
        }
        private global::System.Int32 _RoleTypeID;
        partial void OnRoleTypeIDChanging(global::System.Int32 value);
        partial void OnRoleTypeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RoleTypeName
        {
            get
            {
                return _RoleTypeName;
            }
            set
            {
                OnRoleTypeNameChanging(value);
                ReportPropertyChanging("RoleTypeName");
                _RoleTypeName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("RoleTypeName");
                OnRoleTypeNameChanged();
            }
        }
        private global::System.String _RoleTypeName;
        partial void OnRoleTypeNameChanging(global::System.String value);
        partial void OnRoleTypeNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RoleTypeHier
        {
            get
            {
                return _RoleTypeHier;
            }
            set
            {
                OnRoleTypeHierChanging(value);
                ReportPropertyChanging("RoleTypeHier");
                _RoleTypeHier = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RoleTypeHier");
                OnRoleTypeHierChanged();
            }
        }
        private global::System.Int32 _RoleTypeHier;
        partial void OnRoleTypeHierChanging(global::System.Int32 value);
        partial void OnRoleTypeHierChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean roleTypeActive
        {
            get
            {
                return _roleTypeActive;
            }
            set
            {
                OnroleTypeActiveChanging(value);
                ReportPropertyChanging("roleTypeActive");
                _roleTypeActive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("roleTypeActive");
                OnroleTypeActiveChanged();
            }
        }
        private global::System.Boolean _roleTypeActive;
        partial void OnroleTypeActiveChanging(global::System.Boolean value);
        partial void OnroleTypeActiveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime recCreationDate
        {
            get
            {
                return _recCreationDate;
            }
            set
            {
                OnrecCreationDateChanging(value);
                ReportPropertyChanging("recCreationDate");
                _recCreationDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("recCreationDate");
                OnrecCreationDateChanged();
            }
        }
        private global::System.DateTime _recCreationDate;
        partial void OnrecCreationDateChanging(global::System.DateTime value);
        partial void OnrecCreationDateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Auth564Model", "FK_Roles_RoleTypes", "roles")]
        public EntityCollection<role> roles
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<role>("Auth564Model.FK_Roles_RoleTypes", "roles");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<role>("Auth564Model.FK_Roles_RoleTypes", "roles", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
