//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("Auth564Model", "FK_BlogResponse_Blog", "Blog", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MvcApplication3.Models.Blog), "BlogResponse", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MvcApplication3.Models.BlogResponse), true)]
[assembly: EdmRelationshipAttribute("Auth564Model", "FK_BlogTags_Blog", "Blog", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MvcApplication3.Models.Blog), "BlogTags", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MvcApplication3.Models.BlogTag), true)]

#endregion

namespace MvcApplication3.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Auth564Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Auth564Entities object using the connection string found in the 'Auth564Entities' section of the application configuration file.
        /// </summary>
        public Auth564Entities() : base("name=Auth564Entities", "Auth564Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Auth564Entities object.
        /// </summary>
        public Auth564Entities(string connectionString) : base(connectionString, "Auth564Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Auth564Entities object.
        /// </summary>
        public Auth564Entities(EntityConnection connection) : base(connection, "Auth564Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Blog> Blogs
        {
            get
            {
                if ((_Blogs == null))
                {
                    _Blogs = base.CreateObjectSet<Blog>("Blogs");
                }
                return _Blogs;
            }
        }
        private ObjectSet<Blog> _Blogs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<BlogResponse> BlogResponses
        {
            get
            {
                if ((_BlogResponses == null))
                {
                    _BlogResponses = base.CreateObjectSet<BlogResponse>("BlogResponses");
                }
                return _BlogResponses;
            }
        }
        private ObjectSet<BlogResponse> _BlogResponses;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<BlogTag> BlogTags
        {
            get
            {
                if ((_BlogTags == null))
                {
                    _BlogTags = base.CreateObjectSet<BlogTag>("BlogTags");
                }
                return _BlogTags;
            }
        }
        private ObjectSet<BlogTag> _BlogTags;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Blogs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBlogs(Blog blog)
        {
            base.AddObject("Blogs", blog);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the BlogResponses EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBlogResponses(BlogResponse blogResponse)
        {
            base.AddObject("BlogResponses", blogResponse);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the BlogTags EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBlogTags(BlogTag blogTag)
        {
            base.AddObject("BlogTags", blogTag);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Auth564Model", Name="Blog")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Blog : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Blog object.
        /// </summary>
        /// <param name="blogID">Initial value of the BlogID property.</param>
        /// <param name="recCreationTime">Initial value of the RecCreationTime property.</param>
        public static Blog CreateBlog(global::System.Int32 blogID, global::System.DateTime recCreationTime)
        {
            Blog blog = new Blog();
            blog.BlogID = blogID;
            blog.RecCreationTime = recCreationTime;
            return blog;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BlogID
        {
            get
            {
                return _BlogID;
            }
            set
            {
                if (_BlogID != value)
                {
                    OnBlogIDChanging(value);
                    ReportPropertyChanging("BlogID");
                    _BlogID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("BlogID");
                    OnBlogIDChanged();
                }
            }
        }
        private global::System.Int32 _BlogID;
        partial void OnBlogIDChanging(global::System.Int32 value);
        partial void OnBlogIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BlogText
        {
            get
            {
                return _BlogText;
            }
            set
            {
                OnBlogTextChanging(value);
                ReportPropertyChanging("BlogText");
                _BlogText = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BlogText");
                OnBlogTextChanged();
            }
        }
        private global::System.String _BlogText;
        partial void OnBlogTextChanging(global::System.String value);
        partial void OnBlogTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Mood
        {
            get
            {
                return _Mood;
            }
            set
            {
                OnMoodChanging(value);
                ReportPropertyChanging("Mood");
                _Mood = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Mood");
                OnMoodChanged();
            }
        }
        private global::System.String _Mood;
        partial void OnMoodChanging(global::System.String value);
        partial void OnMoodChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> UserID
        {
            get
            {
                return _UserID;
            }
            set
            {
                OnUserIDChanging(value);
                ReportPropertyChanging("UserID");
                _UserID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserID");
                OnUserIDChanged();
            }
        }
        private Nullable<global::System.Guid> _UserID;
        partial void OnUserIDChanging(Nullable<global::System.Guid> value);
        partial void OnUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> ApplicationID
        {
            get
            {
                return _ApplicationID;
            }
            set
            {
                OnApplicationIDChanging(value);
                ReportPropertyChanging("ApplicationID");
                _ApplicationID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ApplicationID");
                OnApplicationIDChanged();
            }
        }
        private Nullable<global::System.Guid> _ApplicationID;
        partial void OnApplicationIDChanging(Nullable<global::System.Guid> value);
        partial void OnApplicationIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime RecCreationTime
        {
            get
            {
                return _RecCreationTime;
            }
            set
            {
                OnRecCreationTimeChanging(value);
                ReportPropertyChanging("RecCreationTime");
                _RecCreationTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RecCreationTime");
                OnRecCreationTimeChanged();
            }
        }
        private global::System.DateTime _RecCreationTime;
        partial void OnRecCreationTimeChanging(global::System.DateTime value);
        partial void OnRecCreationTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ApplicationName
        {
            get
            {
                return _ApplicationName;
            }
            set
            {
                OnApplicationNameChanging(value);
                ReportPropertyChanging("ApplicationName");
                _ApplicationName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ApplicationName");
                OnApplicationNameChanged();
            }
        }
        private global::System.String _ApplicationName;
        partial void OnApplicationNameChanging(global::System.String value);
        partial void OnApplicationNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PeopleID
        {
            get
            {
                return _PeopleID;
            }
            set
            {
                OnPeopleIDChanging(value);
                ReportPropertyChanging("PeopleID");
                _PeopleID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PeopleID");
                OnPeopleIDChanged();
            }
        }
        private Nullable<global::System.Int32> _PeopleID;
        partial void OnPeopleIDChanging(Nullable<global::System.Int32> value);
        partial void OnPeopleIDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Auth564Model", "FK_BlogResponse_Blog", "BlogResponse")]
        public EntityCollection<BlogResponse> BlogResponses
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<BlogResponse>("Auth564Model.FK_BlogResponse_Blog", "BlogResponse");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<BlogResponse>("Auth564Model.FK_BlogResponse_Blog", "BlogResponse", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Auth564Model", "FK_BlogTags_Blog", "BlogTags")]
        public EntityCollection<BlogTag> BlogTags
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<BlogTag>("Auth564Model.FK_BlogTags_Blog", "BlogTags");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<BlogTag>("Auth564Model.FK_BlogTags_Blog", "BlogTags", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Auth564Model", Name="BlogResponse")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class BlogResponse : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new BlogResponse object.
        /// </summary>
        /// <param name="blogResponseID">Initial value of the BlogResponseID property.</param>
        /// <param name="blogID">Initial value of the BlogID property.</param>
        /// <param name="recCreation">Initial value of the RecCreation property.</param>
        public static BlogResponse CreateBlogResponse(global::System.Int32 blogResponseID, global::System.Int32 blogID, global::System.DateTime recCreation)
        {
            BlogResponse blogResponse = new BlogResponse();
            blogResponse.BlogResponseID = blogResponseID;
            blogResponse.BlogID = blogID;
            blogResponse.RecCreation = recCreation;
            return blogResponse;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BlogResponseID
        {
            get
            {
                return _BlogResponseID;
            }
            set
            {
                if (_BlogResponseID != value)
                {
                    OnBlogResponseIDChanging(value);
                    ReportPropertyChanging("BlogResponseID");
                    _BlogResponseID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("BlogResponseID");
                    OnBlogResponseIDChanged();
                }
            }
        }
        private global::System.Int32 _BlogResponseID;
        partial void OnBlogResponseIDChanging(global::System.Int32 value);
        partial void OnBlogResponseIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BlogID
        {
            get
            {
                return _BlogID;
            }
            set
            {
                OnBlogIDChanging(value);
                ReportPropertyChanging("BlogID");
                _BlogID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BlogID");
                OnBlogIDChanged();
            }
        }
        private global::System.Int32 _BlogID;
        partial void OnBlogIDChanging(global::System.Int32 value);
        partial void OnBlogIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> UserID
        {
            get
            {
                return _UserID;
            }
            set
            {
                OnUserIDChanging(value);
                ReportPropertyChanging("UserID");
                _UserID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserID");
                OnUserIDChanged();
            }
        }
        private Nullable<global::System.Guid> _UserID;
        partial void OnUserIDChanging(Nullable<global::System.Guid> value);
        partial void OnUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime RecCreation
        {
            get
            {
                return _RecCreation;
            }
            set
            {
                OnRecCreationChanging(value);
                ReportPropertyChanging("RecCreation");
                _RecCreation = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RecCreation");
                OnRecCreationChanged();
            }
        }
        private global::System.DateTime _RecCreation;
        partial void OnRecCreationChanging(global::System.DateTime value);
        partial void OnRecCreationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IP
        {
            get
            {
                return _IP;
            }
            set
            {
                OnIPChanging(value);
                ReportPropertyChanging("IP");
                _IP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IP");
                OnIPChanged();
            }
        }
        private global::System.String _IP;
        partial void OnIPChanging(global::System.String value);
        partial void OnIPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Response
        {
            get
            {
                return _Response;
            }
            set
            {
                OnResponseChanging(value);
                ReportPropertyChanging("Response");
                _Response = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Response");
                OnResponseChanged();
            }
        }
        private global::System.String _Response;
        partial void OnResponseChanging(global::System.String value);
        partial void OnResponseChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Auth564Model", "FK_BlogResponse_Blog", "Blog")]
        public Blog Blog
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Blog>("Auth564Model.FK_BlogResponse_Blog", "Blog").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Blog>("Auth564Model.FK_BlogResponse_Blog", "Blog").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Blog> BlogReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Blog>("Auth564Model.FK_BlogResponse_Blog", "Blog");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Blog>("Auth564Model.FK_BlogResponse_Blog", "Blog", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Auth564Model", Name="BlogTag")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class BlogTag : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new BlogTag object.
        /// </summary>
        /// <param name="blogID">Initial value of the BlogID property.</param>
        /// <param name="tagID">Initial value of the TagID property.</param>
        /// <param name="userName">Initial value of the UserName property.</param>
        public static BlogTag CreateBlogTag(global::System.Int32 blogID, global::System.Int32 tagID, global::System.String userName)
        {
            BlogTag blogTag = new BlogTag();
            blogTag.BlogID = blogID;
            blogTag.TagID = tagID;
            blogTag.UserName = userName;
            return blogTag;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BlogID
        {
            get
            {
                return _BlogID;
            }
            set
            {
                if (_BlogID != value)
                {
                    OnBlogIDChanging(value);
                    ReportPropertyChanging("BlogID");
                    _BlogID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("BlogID");
                    OnBlogIDChanged();
                }
            }
        }
        private global::System.Int32 _BlogID;
        partial void OnBlogIDChanging(global::System.Int32 value);
        partial void OnBlogIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TagID
        {
            get
            {
                return _TagID;
            }
            set
            {
                if (_TagID != value)
                {
                    OnTagIDChanging(value);
                    ReportPropertyChanging("TagID");
                    _TagID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TagID");
                    OnTagIDChanged();
                }
            }
        }
        private global::System.Int32 _TagID;
        partial void OnTagIDChanging(global::System.Int32 value);
        partial void OnTagIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                if (_UserName != value)
                {
                    OnUserNameChanging(value);
                    ReportPropertyChanging("UserName");
                    _UserName = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("UserName");
                    OnUserNameChanged();
                }
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> UserID
        {
            get
            {
                return _UserID;
            }
            set
            {
                OnUserIDChanging(value);
                ReportPropertyChanging("UserID");
                _UserID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserID");
                OnUserIDChanged();
            }
        }
        private Nullable<global::System.Guid> _UserID;
        partial void OnUserIDChanging(Nullable<global::System.Guid> value);
        partial void OnUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> peoplID
        {
            get
            {
                return _peoplID;
            }
            set
            {
                OnpeoplIDChanging(value);
                ReportPropertyChanging("peoplID");
                _peoplID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("peoplID");
                OnpeoplIDChanged();
            }
        }
        private Nullable<global::System.Int32> _peoplID;
        partial void OnpeoplIDChanging(Nullable<global::System.Int32> value);
        partial void OnpeoplIDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Auth564Model", "FK_BlogTags_Blog", "Blog")]
        public Blog Blog
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Blog>("Auth564Model.FK_BlogTags_Blog", "Blog").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Blog>("Auth564Model.FK_BlogTags_Blog", "Blog").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Blog> BlogReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Blog>("Auth564Model.FK_BlogTags_Blog", "Blog");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Blog>("Auth564Model.FK_BlogTags_Blog", "Blog", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
